from settings import settings_blueprint
from account import account_blueprint
from home import home_blueprint
from item import item_blueprint
from items import items_blueprint
from template import template_blueprint
from system_messages import system_messages_blueprint
from real_item import real_item_blueprint